a = input('Digite um numero: ')
print("Tipo primitivo:",type(a).__name__)
print("É um numero: ",a.isnumeric())
print("É Alfanumerico: ",a.isalnum())
print("É alfabetico: ",a.isalpha())
print("É minusculo: ",a.islower())
print("É Decimal:",a.isdecimal())
print("É maiusculo: ",a.isupper())
print("Está com a primeira letra maiuscula: ",a.istitle())